### ISSUE TITLE
Videreudvikling af plugin "Relative date"

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-availability_relativedate#1]
@superfoght commented on [Mon Apr 04 2022](https://github.com/praxisdigital/moodle-opgaver/issues/79)

Jeg har i første ombæring fået til opgave at vi skal estimere nedenstående fra denne sag: https://praxisdigital.zendesk.com/agent/tickets/38743

Det er dette plugin: https://moodle.org/plugins/availability_relativedate det drejer sig om. 

Tue skriver "Tænker at vi gør det selv og bruger noget af deres klippekort på det. Bed Moodle team om at kigge på et estimat - men at få det ind i pluginnet hos 3. part har vi brug for en use case. De acceptere nemlig kun feature proposals . Så bed lig om at uddybe hvad use casen er. "

Så vi må lige tage op hvad vi konkret gør, efter dette er blevet estimeret i timer. 

Vil I undersøge hvad det koster, om muligt, at få funktionen ”After course end date” tilknyttet denne plugin ”Relative date”;

![image.png](https://images.zenhubusercontent.com/61fb94a8e26aff511b3cf27c/b185f0ef-0a4a-4cdb-b550-b1b75b02557a)

Vi har behov for at kursusbeviser og evalueringer automatisk bliver udsendt til kursusdeltagere efter course end date. Det virker uprofessionelt ar deltagerne på et kursus modtager eks. evalueringsadgang inden kurset er afsluttet. (Vi har ikke mulighed for at skrive en ”fake” senere course end date, da datoerne for kursusaholdelsen fremgår af kursussiderne)

 Dvs. at vi i course-settings kan sætte en ”course end date”, som plugin ”relative date” kan bruge.

![image.png](https://images.zenhubusercontent.com/61fb94a8e26aff511b3cf27c/92d2ccbb-0f9c-48a7-bb78-092d02deb626)

![image.png](https://images.zenhubusercontent.com/61fb94a8e26aff511b3cf27c/bd138144-0176-46f3-ae8f-95439a4731dd)

**Comment by frederikmillingpytlick** [comment]
I've created a PR over at https://github.com/ewallah/moodle-availability_relativedate/pull/16

**Comment by frederikmillingpytlick** [comment]
My fix has been merged into v4.0.3 of the plugin. 

@Mikkeljeppesen1 could you make sure it's updated on the sites using it?

Version: 2022070903

https://morris.praxis.dk/plugin/738
https://moodle.org/plugins/pluginversions.php?plugin=availability_relativedate

**Comment by Mikkeljeppesen1** [comment]
@frederikmillingpytlick it will be released later this evening
