### ISSUE TITLE
Error when using Pulse activity

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-availability_relativedate#2]
If you copy the PULSE activity to sharing cart and inserts it again you get the following error. 

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/e52a5c48-2490-4292-9344-406b7bcd8253)
- test course https://campus.ida.dk/course/view.php?id=172

From the customer: 

Det lader til at man ødelægger alle kurser ved at kopiere fra delekurven. Aktiviteten er i øvrigt den Pulse-aktivitet jeg har oprettet her:

https://campus.ida.dk/course/modedit.php?update=3876&return=0&sr=2

Efter at jeg forsøgte at indsætte en aktivitet vha delekurven, kan jeg ikke længere få adgang til dette kursus: https://campus.ida.dk/course/management.php?categoryid=129&courseid=281 (skab balance i det hybride arbejdsliv)

https://app-eu1.hubspot.com/contacts/25645903/record/0-5/1603942384

**Comment by neeesn** [comment]
Pulse på moodle.org -

**Comment by AraPraxis** [comment]
The error was in relativedate..

When an activity (A) is accessible 1 day after activity (B) is marked as done. Then it will of course open for the individual user.
If you would use sharing cart or re-create the course with only activity (A) - Then activity (B) would be missing, and the code didn't rely on that happening. This is now fixed

**Comment by AraPraxis** [comment]
### Fixed
- Error that would occur, when adding an activity with relative date on another activity, and hereafter "porting" the first activity to another course

## Testing

1. Create 2 courses
2. Create 2 activities (A & B)
2.1. B should have a restriction set, as relative date, on activity A (see picture for clarification)
3. Copy activity B to the other course
3.1. This can be done with sharing cart plugin or by only selecting activity B in course backup/restore
4. When the activity is added, it should tell the admin that there's an activity missing (See second picture)
5. If both activities is added (At the same time with backup/restore), then it should not be missing.

## Info

Version: Moodle 4.0 - 4.2
Branch: ara_GH_main-2
Pull: https://github.com/praxisdigital/moodle-availability_relativedate/pull/3




![Image](https://github.com/praxisdigital/moodle-availability_relativedate/assets/89771146/b76f4593-36a0-461b-9df6-18d9c8e93e43)



![Image](https://github.com/praxisdigital/moodle-availability_relativedate/assets/89771146/ef9969b8-1cb6-4dc6-9be0-eaa0c4bdde89)

**Comment by AraPraxis** [comment]
Awaiting further release until update is approved at parent GitHub

**Comment by AraPraxis** [comment]
Tests failing on parent repository
(Naming schemes are different & 1 test displays wrong info)

**Comment by AraPraxis** [comment]
## Release

The error was fixed by ewallah himself, before I took a look at it.

New tag: v4.0.8
Moodle: 3.11 - 4.2

I've created a fork of the plugin, but for constant updates I would prefer we used Ewallah's GitHub Repo
